# Generated by Django 4.2.22 on 2025-06-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='channel_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
